name: runs without dependiecies

on: push

jobs:
  print:

   runs-on: ubuntu-latest

   steps:
     - name: job1
       run: echo "job 1"

  build:

   runs-on: ubuntu-latest
     
   steps:
     - name : job2
       run: echo "job2"