name: practice for uses command

on : push

jobs:
  print:
    runs-on : ubuntu-latest

    steps:
      - name: testing phase 
        uses: actions/checkout@v5

      - name: checking code
        run: ls -l



